# Generated by Django 3.2.3 on 2021-10-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211016_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Phoneno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('busName', models.CharField(max_length=50)),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('stime', models.TimeField()),
                ('dtime', models.TimeField()),
                ('totFare', models.IntegerField()),
                ('busType', models.TextField()),
            ],
        ),
    ]
