# Generated by Django 3.2.3 on 2021-10-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='busname',
            new_name='busName',
        ),
    ]
