# Generated by Django 3.2.3 on 2021-10-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_passenger_seatnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='date',
            field=models.DateField(default='2021-1-1'),
            preserve_default=False,
        ),
    ]
