# Generated by Django 3.2.3 on 2021-10-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_passenger_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='Uname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
